{\rtf1\ansi\ansicpg1252\cocoartf2513
\cocoatextscaling0\cocoaplatform0{\fonttbl\f0\fnil\fcharset0 HelveticaNeue;\f1\froman\fcharset0 TimesNewRomanPSMT;}
{\colortbl;\red255\green255\blue255;\red18\green19\blue24;\red225\green224\blue224;\red0\green0\blue0;
}
{\*\expandedcolortbl;;\cssrgb\c8627\c9804\c12157;\cssrgb\c90588\c90196\c90196;\cssrgb\c0\c0\c0;
}
\paperw11900\paperh16840\margl1440\margr1440\vieww14440\viewh11440\viewkind0
\deftab720
\pard\pardeftab720\partightenfactor0

\f0\fs28 \cf2 \cb3 \expnd0\expndtw0\kerning0
--Create USER1
\f1\fs32 \cf4 \

\f0\fs28 \cf2 CREATE USER USER1 PASSWORD Password1 no force_first_password_change;
\f1\fs32 \cf4 \

\f0\fs28 \cf2 \'a0
\f1\fs32 \cf4 \

\f0\fs28 \cf2 --To verify that the user was created, enter the following command.
\f1\fs32 \cf4 \

\f0\fs28 \cf2 SELECT USER_NAME FROM USERS;
\f1\fs32 \cf4 \

\f0\fs28 \cf2 \'a0
\f1\fs32 \cf4 \

\f0\fs28 \cf2 --Also notice that a schema with the same name is created for this user.
\f1\fs32 \cf4 \

\f0\fs28 \cf2 SELECT SCHEMA_NAME FROM SCHEMAS;
\f1\fs32 \cf4 \

\f0\fs28 \cf2 \'a0
\f1\fs32 \cf4 \

\f0\fs28 \cf2 --Check USER1 Schema
\f1\fs32 \cf4 \

\f0\fs28 \cf2 CONNECT USER1 PASSWORD Password1;
\f1\fs32 \cf4 \

\f0\fs28 \cf2 SELECT CURRENT_USER, CURRENT_SCHEMA FROM DUMMY;
\f1\fs32 \cf4 \

\f0\fs28 \cf2 \'a0
\f1\fs32 \cf4 \

\f0\fs28 \cf2 --Create Tables and upload data
\f1\fs32 \cf4 \

\f0\fs28 \cf2 SET SCHEMA USER1;
\f1\fs32 \cf4 \

\f0\fs28 \cf2 CREATE COLUMN TABLE HOTEL(
\f1\fs32 \cf4 \

\f0\fs28 \cf2 \'a0 hno INTEGER PRIMARY KEY,
\f1\fs32 \cf4 \

\f0\fs28 \cf2 \'a0 name NVARCHAR(50) NOT NULL,
\f1\fs32 \cf4 \

\f0\fs28 \cf2 \'a0 address NVARCHAR(40) NOT NULL,
\f1\fs32 \cf4 \

\f0\fs28 \cf2 \'a0 city NVARCHAR(30) NOT NULL,
\f1\fs32 \cf4 \

\f0\fs28 \cf2 \'a0 state NVARCHAR(2) NOT NULL,
\f1\fs32 \cf4 \

\f0\fs28 \cf2 \'a0 zip NVARCHAR(6)
\f1\fs32 \cf4 \

\f0\fs28 \cf2 );
\f1\fs32 \cf4 \

\f0\fs28 \cf2 CREATE COLUMN TABLE ROOM(
\f1\fs32 \cf4 \

\f0\fs28 \cf2 \'a0 hno INTEGER,
\f1\fs32 \cf4 \

\f0\fs28 \cf2 \'a0 type NVARCHAR(6),
\f1\fs32 \cf4 \

\f0\fs28 \cf2 \'a0 free NUMERIC(3),
\f1\fs32 \cf4 \

\f0\fs28 \cf2 \'a0 price NUMERIC(6, 2),
\f1\fs32 \cf4 \

\f0\fs28 \cf2 \'a0 PRIMARY KEY (hno, type),
\f1\fs32 \cf4 \

\f0\fs28 \cf2 \'a0 FOREIGN KEY (hno) REFERENCES HOTEL
\f1\fs32 \cf4 \

\f0\fs28 \cf2 );
\f1\fs32 \cf4 \

\f0\fs28 \cf2 CREATE COLUMN TABLE CUSTOMER(
\f1\fs32 \cf4 \

\f0\fs28 \cf2 \'a0 cno INTEGER PRIMARY KEY,
\f1\fs32 \cf4 \

\f0\fs28 \cf2 \'a0 title NVARCHAR(7),
\f1\fs32 \cf4 \

\f0\fs28 \cf2 \'a0 firstname NVARCHAR(20),
\f1\fs32 \cf4 \

\f0\fs28 \cf2 \'a0 name NVARCHAR(40) NOT NULL,
\f1\fs32 \cf4 \

\f0\fs28 \cf2 \'a0 address NVARCHAR(40) NOT NULL,
\f1\fs32 \cf4 \

\f0\fs28 \cf2 \'a0 zip NVARCHAR(6)
\f1\fs32 \cf4 \

\f0\fs28 \cf2 );
\f1\fs32 \cf4 \

\f0\fs28 \cf2 CREATE COLUMN TABLE RESERVATION(
\f1\fs32 \cf4 \

\f0\fs28 \cf2 \'a0 resno INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
\f1\fs32 \cf4 \

\f0\fs28 \cf2 \'a0 rno INTEGER NOT NULL,
\f1\fs32 \cf4 \

\f0\fs28 \cf2 \'a0 cno INTEGER,
\f1\fs32 \cf4 \

\f0\fs28 \cf2 \'a0 hno INTEGER,
\f1\fs32 \cf4 \

\f0\fs28 \cf2 \'a0 type NVARCHAR(6),
\f1\fs32 \cf4 \

\f0\fs28 \cf2 \'a0 arrival DATE NOT NULL,
\f1\fs32 \cf4 \

\f0\fs28 \cf2 \'a0 departure DATE NOT NULL,
\f1\fs32 \cf4 \

\f0\fs28 \cf2 \'a0 PRIMARY KEY (
\f1\fs32 \cf4 \

\f0\fs28 \cf2 \'a0\'a0\'a0 "RESNO", "ARRIVAL"
\f1\fs32 \cf4 \

\f0\fs28 \cf2 \'a0 ),
\f1\fs32 \cf4 \

\f0\fs28 \cf2 \'a0 FOREIGN KEY(hno) REFERENCES HOTEL,
\f1\fs32 \cf4 \

\f0\fs28 \cf2 \'a0 FOREIGN KEY(cno) REFERENCES CUSTOMER
\f1\fs32 \cf4 \

\f0\fs28 \cf2 );
\f1\fs32 \cf4 \

\f0\fs28 \cf2 CREATE COLUMN TABLE MAINTENANCE(
\f1\fs32 \cf4 \

\f0\fs28 \cf2 \'a0 mno INTEGER PRIMARY KEY,
\f1\fs32 \cf4 \

\f0\fs28 \cf2 \'a0 hno INTEGER,
\f1\fs32 \cf4 \

\f0\fs28 \cf2 \'a0 description NVARCHAR(100),
\f1\fs32 \cf4 \

\f0\fs28 \cf2 \'a0 date_performed DATE,
\f1\fs32 \cf4 \

\f0\fs28 \cf2 \'a0 performed_by NVARCHAR(40)
\f1\fs32 \cf4 \

\f0\fs28 \cf2 );
\f1\fs32 \cf4 \

\f0\fs28 \cf2 \'a0
\f1\fs32 \cf4 \

\f0\fs28 \cf2 CREATE VIEW ALL_RESERVATIONS
\f1\fs32 \cf4 \

\f0\fs28 \cf2 \'a0\'a0 AS SELECT
\f1\fs32 \cf4 \

\f0\fs28 \cf2 \'a0\'a0\'a0\'a0\'a0 R.RESNO,
\f1\fs32 \cf4 \

\f0\fs28 \cf2 \'a0\'a0\'a0\'a0\'a0 R.ARRIVAL,
\f1\fs32 \cf4 \

\f0\fs28 \cf2 \'a0\'a0\'a0\'a0\'a0 DAYS_BETWEEN (R.ARRIVAL, R.DEPARTURE) as "Nights",
\f1\fs32 \cf4 \

\f0\fs28 \cf2 \'a0\'a0\'a0\'a0\'a0 H.NAME as "HOTEL",
\f1\fs32 \cf4 \

\f0\fs28 \cf2 \'a0\'a0\'a0\'a0\'a0 CUS.TITLE,
\f1\fs32 \cf4 \

\f0\fs28 \cf2 \'a0\'a0\'a0\'a0\'a0 CUS.FIRSTNAME AS "FIRST NAME",
\f1\fs32 \cf4 \

\f0\fs28 \cf2 \'a0\'a0\'a0\'a0\'a0 CUS.NAME AS "LAST NAME"
\f1\fs32 \cf4 \

\f0\fs28 \cf2 \'a0\'a0\'a0 FROM
\f1\fs32 \cf4 \

\f0\fs28 \cf2 \'a0\'a0\'a0\'a0\'a0 RESERVATION AS R
\f1\fs32 \cf4 \

\f0\fs28 \cf2 \'a0\'a0\'a0\'a0\'a0 LEFT OUTER JOIN
\f1\fs32 \cf4 \

\f0\fs28 \cf2 \'a0\'a0\'a0 \'a0\'a0HOTEL AS H
\f1\fs32 \cf4 \

\f0\fs28 \cf2 \'a0\'a0\'a0\'a0\'a0 ON H.HNO = R.HNO
\f1\fs32 \cf4 \

\f0\fs28 \cf2 \'a0\'a0\'a0\'a0\'a0 LEFT OUTER JOIN
\f1\fs32 \cf4 \

\f0\fs28 \cf2 \'a0\'a0\'a0\'a0\'a0 CUSTOMER AS CUS
\f1\fs32 \cf4 \

\f0\fs28 \cf2 \'a0\'a0\'a0\'a0\'a0 ON CUS.CNO = R.CNO
\f1\fs32 \cf4 \

\f0\fs28 \cf2 \'a0\'a0\'a0 ORDER BY
\f1\fs32 \cf4 \

\f0\fs28 \cf2 \'a0\'a0\'a0\'a0\'a0 H.NAME ASC,
\f1\fs32 \cf4 \

\f0\fs28 \cf2 \'a0\'a0\'a0\'a0\'a0 R.ARRIVAL DESC;
\f1\fs32 \cf4 \

\f0\fs28 \cf2 \'a0
\f1\fs32 \cf4 \

\f0\fs28 \cf2 INSERT INTO HOTEL VALUES(10, 'Congress', '155 Beechwood St.', 'Seattle', 'WA', '20005');
\f1\fs32 \cf4 \

\f0\fs28 \cf2 INSERT INTO HOTEL VALUES(11, 'Regency', '477 17th Avenue', 'Seattle', 'WA', '20037');
\f1\fs32 \cf4 \

\f0\fs28 \cf2 INSERT INTO HOTEL VALUES(12, 'Long Island', '1499 Grove Street', 'Long Island', 'NY', '11788');
\f1\fs32 \cf4 \

\f0\fs28 \cf2 INSERT INTO HOTEL VALUES(13, 'Empire State', '65 Yellowstone Dr.', 'Albany', 'NY', '12203');
\f1\fs32 \cf4 \

\f0\fs28 \cf2 INSERT INTO HOTEL VALUES(14, 'Midtown', '12 Barnard St.', 'New York', 'NY', '10019');
\f1\fs32 \cf4 \

\f0\fs28 \cf2 INSERT INTO HOTEL VALUES(15, 'Eighth Avenue', '112 8th Avenue', 'New York', 'NY', '10019');
\f1\fs32 \cf4 \

\f0\fs28 \cf2 INSERT INTO HOTEL VALUES(16, 'Lake Michigan', '354 OAK Terrace', 'Chicago', 'IL', '60601');
\f1\fs32 \cf4 \

\f0\fs28 \cf2 INSERT INTO HOTEL VALUES(17, 'Airport', '650 C Parkway', 'Rosemont', 'IL', '60018');
\f1\fs32 \cf4 \

\f0\fs28 \cf2 INSERT INTO HOTEL VALUES(18, 'Sunshine', '200 Yellowstone Dr.', 'Clearwater', 'FL', '33575');
\f1\fs32 \cf4 \

\f0\fs28 \cf2 INSERT INTO HOTEL VALUES(19, 'Beach', '1980 34th St.', 'Daytona Beach', 'FL', '32018');
\f1\fs32 \cf4 \

\f0\fs28 \cf2 INSERT INTO HOTEL VALUES(20, 'Atlantic', '111 78th St.', 'Deerfield Beach', 'FL', '33441');
\f1\fs32 \cf4 \

\f0\fs28 \cf2 INSERT INTO HOTEL VALUES(21, 'Long Beach', '35 Broadway', 'Long Beach', 'CA', '90804');
\f1\fs32 \cf4 \

\f0\fs28 \cf2 INSERT INTO HOTEL VALUES(22, 'Indian Horse', '16 MAIN STREET', 'Palm Springs', 'CA', '92262');
\f1\fs32 \cf4 \

\f0\fs28 \cf2 INSERT INTO HOTEL VALUES(23, 'Star', '13 Beechwood Place', 'Hollywood', 'CA', '90029');
\f1\fs32 \cf4 \

\f0\fs28 \cf2 INSERT INTO HOTEL VALUES(24, 'River Boat', '788 MAIN STREET', 'New Orleans', 'LA', '70112');
\f1\fs32 \cf4 \

\f0\fs28 \cf2 INSERT INTO HOTEL VALUES(25, 'Ocean Star', '45 Pacific Avenue', 'Atlantic City', 'NJ', '08401');
\f1\fs32 \cf4 \

\f0\fs28 \cf2 INSERT INTO HOTEL VALUES(26, 'Bella Ciente', '1407 Marshall Ave', 'Longview', 'TX', '75601');
\f1\fs32 \cf4 \

\f0\fs28 \cf2 \'a0
\f1\fs32 \cf4 \

\f0\fs28 \cf2 INSERT INTO ROOM VALUES(10, 'single', 20, 135.00);
\f1\fs32 \cf4 \

\f0\fs28 \cf2 INSERT INTO ROOM VALUES(10, 'double', 45, 200.00);
\f1\fs32 \cf4 \

\f0\fs28 \cf2 INSERT INTO ROOM VALUES(12, 'single', 10, 70.00);
\f1\fs32 \cf4 \

\f0\fs28 \cf2 INSERT INTO ROOM VALUES(12, 'double', 13, 100.00);
\f1\fs32 \cf4 \

\f0\fs28 \cf2 INSERT INTO ROOM VALUES(13, 'single', 12, 45.00);
\f1\fs32 \cf4 \

\f0\fs28 \cf2 INSERT INTO ROOM VALUES(13, 'double', 15, 80.00);
\f1\fs32 \cf4 \

\f0\fs28 \cf2 INSERT INTO ROOM VALUES(14, 'single', 20, 85.00);
\f1\fs32 \cf4 \

\f0\fs28 \cf2 INSERT INTO ROOM VALUES(14, 'double', 35, 140.00);
\f1\fs32 \cf4 \

\f0\fs28 \cf2 INSERT INTO ROOM VALUES(15, 'single', 50, 105.00);
\f1\fs32 \cf4 \

\f0\fs28 \cf2 INSERT INTO ROOM VALUES(15, 'double', 230, 180.00);
\f1\fs32 \cf4 \

\f0\fs28 \cf2 INSERT INTO ROOM VALUES(15, 'suite', 12, 500.00);
\f1\fs32 \cf4 \

\f0\fs28 \cf2 INSERT INTO ROOM VALUES(16, 'single', 10, 120.00);
\f1\fs32 \cf4 \

\f0\fs28 \cf2 INSERT INTO ROOM VALUES(16, 'double', 39, 200.00);
\f1\fs32 \cf4 \

\f0\fs28 \cf2 INSERT INTO ROOM VALUES(16, 'suite', 20, 500.00);
\f1\fs32 \cf4 \

\f0\fs28 \cf2 INSERT INTO ROOM VALUES(17, 'single', 4, 115.00);
\f1\fs32 \cf4 \

\f0\fs28 \cf2 INSERT INTO ROOM VALUES(17, 'double', 11, 180.00);
\f1\fs32 \cf4 \

\f0\fs28 \cf2 INSERT INTO ROOM VALUES(18, 'single', 15, 90.00);
\f1\fs32 \cf4 \

\f0\fs28 \cf2 INSERT INTO ROOM VALUES(18, 'double', 19, 150.00);
\f1\fs32 \cf4 \

\f0\fs28 \cf2 INSERT INTO ROOM VALUES(18, 'suite', 5, 400.00);
\f1\fs32 \cf4 \

\f0\fs28 \cf2 INSERT INTO ROOM VALUES(19, 'single', 45, 90.00);
\f1\fs32 \cf4 \

\f0\fs28 \cf2 INSERT INTO ROOM VALUES(19, 'double', 145, 150.00);
\f1\fs32 \cf4 \

\f0\fs28 \cf2 INSERT INTO ROOM VALUES(19, 'suite', 60, 300.00);
\f1\fs32 \cf4 \

\f0\fs28 \cf2 INSERT INTO ROOM VALUES(20, 'single', 11, 60.00);
\f1\fs32 \cf4 \

\f0\fs28 \cf2 INSERT INTO ROOM VALUES(20, 'double', 24, 100.00);
\f1\fs32 \cf4 \

\f0\fs28 \cf2 INSERT INTO ROOM VALUES(21, 'single', 2, 70.00);
\f1\fs32 \cf4 \

\f0\fs28 \cf2 INSERT INTO ROOM VALUES(21, 'double', 10, 130.00);
\f1\fs32 \cf4 \

\f0\fs28 \cf2 INSERT INTO ROOM VALUES(22, 'single', 34, 80.00);
\f1\fs32 \cf4 \

\f0\fs28 \cf2 INSERT INTO ROOM VALUES(22, 'double', 78, 140.00);
\f1\fs32 \cf4 \

\f0\fs28 \cf2 INSERT INTO ROOM VALUES(22, 'suite', 55, 350.00);
\f1\fs32 \cf4 \

\f0\fs28 \cf2 INSERT INTO ROOM VALUES(23, 'single', 89, 160.00);
\f1\fs32 \cf4 \

\f0\fs28 \cf2 INSERT INTO ROOM VALUES(23, 'double', 300, 270.00);
\f1\fs32 \cf4 \

\f0\fs28 \cf2 INSERT INTO ROOM VALUES(23, 'suite', 100, 700.00);
\f1\fs32 \cf4 \

\f0\fs28 \cf2 INSERT INTO ROOM VALUES(24, 'single', 10, 125.00);
\f1\fs32 \cf4 \

\f0\fs28 \cf2 INSERT INTO ROOM VALUES(24, 'double', 9, 200.00);
\f1\fs32 \cf4 \

\f0\fs28 \cf2 INSERT INTO ROOM VALUES(24, 'suite', 78, 600.00);
\f1\fs32 \cf4 \

\f0\fs28 \cf2 INSERT INTO ROOM VALUES(25, 'single', 44, 100.00);
\f1\fs32 \cf4 \

\f0\fs28 \cf2 INSERT INTO ROOM VALUES(25, 'double', 115, 190.00);
\f1\fs32 \cf4 \

\f0\fs28 \cf2 INSERT INTO ROOM VALUES(25, 'suite', 6, 450.00);
\f1\fs32 \cf4 \

\f0\fs28 \cf2 \'a0
\f1\fs32 \cf4 \

\f0\fs28 \cf2 INSERT INTO CUSTOMER VALUES(1000, 'Mrs', 'Jenny', 'Porter', '1340 N. Ash Street, #3', '10580');
\f1\fs32 \cf4 \

\f0\fs28 \cf2 INSERT INTO CUSTOMER VALUES(1001, 'Mr', 'Peter', 'Brown', '1001 34th St., APT.3', '48226');
\f1\fs32 \cf4 \

\f0\fs28 \cf2 INSERT INTO CUSTOMER VALUES(1002, 'Company', NULL, 'Datasoft', '486 Maple St.', '90018');
\f1\fs32 \cf4 \

\f0\fs28 \cf2 INSERT INTO CUSTOMER VALUES(1003, 'Mrs', 'Rose', 'Brian', '500 Yellowstone Drive, #2', '75243');
\f1\fs32 \cf4 \

\f0\fs28 \cf2 INSERT INTO CUSTOMER VALUES(1004, 'Mrs', 'Mary', 'Griffith', '3401 Elder Lane', '20005');
\f1\fs32 \cf4 \

\f0\fs28 \cf2 INSERT INTO CUSTOMER VALUES(1005, 'Mr', 'Martin', 'Randolph', '340 MAIN STREET, #7', '60615');
\f1\fs32 \cf4 \

\f0\fs28 \cf2 INSERT INTO CUSTOMER VALUES(1006, 'Mrs', 'Sally', 'Smith', '250 Curtis Street', '75243');
\f1\fs32 \cf4 \

\f0\fs28 \cf2 INSERT INTO CUSTOMER VALUES(1007, 'Mr', 'Mike', 'Jackson', '133 BROADWAY APT. 1', '45211');
\f1\fs32 \cf4 \

\f0\fs28 \cf2 INSERT INTO CUSTOMER VALUES(1008, 'Mrs', 'Rita', 'Doe', '2000 Humboldt St., #6', '97213');
\f1\fs32 \cf4 \

\f0\fs28 \cf2 INSERT INTO CUSTOMER VALUES(1009, 'Mr', 'George', 'Howe', '111 B Parkway, #23', '75243');
\f1\fs32 \cf4 \

\f0\fs28 \cf2 INSERT INTO CUSTOMER VALUES(1010, 'Mr', 'Frank', 'Miller', '27 5th St., 76', '95054');
\f1\fs32 \cf4 \

\f0\fs28 \cf2 INSERT INTO CUSTOMER VALUES(1011, 'Mrs', 'Susan', 'Baker', '200 MAIN STREET, #94', '90018');
\f1\fs32 \cf4 \

\f0\fs28 \cf2 INSERT INTO CUSTOMER VALUES(1012, 'Mr', 'Joseph', 'Peters', '700 S. Ash St., APT.12', '92714');
\f1\fs32 \cf4 \

\f0\fs28 \cf2 INSERT INTO CUSTOMER VALUES(1013, 'Company', NULL, 'TOOLware', '410 Mariposa St., #10', '20019');
\f1\fs32 \cf4 \

\f0\fs28 \cf2 INSERT INTO CUSTOMER VALUES(1014, 'Mr', 'Antony', 'Jenkins', '55 A Parkway, #15', '20903');
\f1\fs32 \cf4 \

\f0\fs28 \cf2 INSERT INTO RESERVATION VALUES(1, 100, 1000, 11, 'single', '2020-12-24', '2020-12-27');
\f1\fs32 \cf4 \

\f0\fs28 \cf2 INSERT INTO RESERVATION VALUES(2, 110, 1001, 11, 'double', '2020-12-24', '2021-01-03');
\f1\fs32 \cf4 \

\f0\fs28 \cf2 INSERT INTO RESERVATION VALUES(3, 120, 1002, 15, 'suite', '2020-11-14', '2020-11-18');
\f1\fs32 \cf4 \

\f0\fs28 \cf2 INSERT INTO RESERVATION VALUES(4, 130, 1009, 21, 'single', '2019-02-01', '2019-02-03');
\f1\fs32 \cf4 \

\f0\fs28 \cf2 INSERT INTO RESERVATION VALUES(5, 150, 1006, 17, 'double', '2019-03-14', '2019-03-24');
\f1\fs32 \cf4 \

\f0\fs28 \cf2 INSERT INTO RESERVATION VALUES(6, 140, 1013, 20, 'double', '2020-04-12', '2020-04-30');
\f1\fs32 \cf4 \

\f0\fs28 \cf2 INSERT INTO RESERVATION VALUES(7, 160, 1011, 17, 'single', '2020-04-12', '2020-04-15');
\f1\fs32 \cf4 \

\f0\fs28 \cf2 INSERT INTO RESERVATION VALUES(8, 170, 1014, 25, 'suite', '2020-09-01', '2020-09-03');
\f1\fs32 \cf4 \

\f0\fs28 \cf2 INSERT INTO RESERVATION VALUES(9, 180, 1001, 22, 'double', '2020-12-23', '2021-01-08');
\f1\fs32 \cf4 \

\f0\fs28 \cf2 INSERT INTO RESERVATION VALUES(10, 190, 1013, 24, 'double', '2020-11-14', '2020-11-17');
\f1\fs32 \cf4 \

\f0\fs28 \cf2 \'a0
\f1\fs32 \cf4 \

\f0\fs28 \cf2 INSERT INTO MAINTENANCE VALUES(10, 24, 'Replace pool liner and pump', '2019-03-21', 'Discount Pool Supplies');
\f1\fs32 \cf4 \

\f0\fs28 \cf2 INSERT INTO MAINTENANCE VALUES(11, 25, 'Renovate the bar area.\'a0 Replace TV and speakers', '2020-11-29', 'TV and Audio Superstore');
\f1\fs32 \cf4 \

\f0\fs28 \cf2 INSERT INTO MAINTENANCE VALUES(12, 26, 'Roof repair due to storm', null, null);
\f1\fs32 \cf4 \

\f0\fs28 \cf2 \'a0
\f1\fs32 \cf4 \

\f0\fs28 \cf2 --Create lower case public synonym for Langchain SQL Agents use case
\f1\fs32 \cf4 \

\f0\fs28 \cf2 CREATE PUBLIC SYNONYM hotel FOR USER1.HOTEL;
\f1\fs32 \cf4 \

\f0\fs28 \cf2 CREATE PUBLIC SYNONYM reservation FOR USER1.RESERVATION;
\f1\fs32 \cf4 \

\f0\fs28 \cf2 CREATE PUBLIC SYNONYM room FOR USER1.ROOM;
\f1\fs32 \cf4 \

\f0\fs28 \cf2 CREATE PUBLIC SYNONYM maintenance FOR USER1.MAINTENANCE;
\f1\fs32 \cf4 \

\f0\fs28 \cf2 CREATE PUBLIC SYNONYM customer FOR USER1.CUSTOMER;
\f1\fs32 \cf4 \

\f0\fs28 \cf2 \'a0
\f1\fs32 \cf4 \

\f0\fs28 \cf2 --Verify the table entries
\f1\fs32 \cf4 \

\f0\fs28 \cf2 SELECT SCHEMA_NAME, OBJECT_NAME, OBJECT_TYPE, OWNER_NAME FROM "PUBLIC"."OWNERSHIP" WHERE OWNER_NAME = 'USER1';
\f1\fs32 \cf4 \

\f0\fs28 \cf2 \'a0
\f1\fs32 \cf4 \

\f0\fs28 \cf2 SELECT * FROM USER1.HOTEL;
\f1\fs32 \cf4 \
}